version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      react:
        patterns:
          - react
          - react-dom
        update-types:
          - minor
          - patch
      development-tooling:
        dependency-type: development
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
